# (APPENDIX) Appendix {-} 

# FishPath Tool Frequently Asked Questions (FAQs)

##### How do I submit feedback about content or user experience? {#faq-feedback}

FishPath benefits from the expertise and feedback of the global community of FishPath tool users. Users are encouraged to submit feedback about the FishPath tool, ultimately helping to improve the tool. There are two ways to submit feedback:

1.	The “Submit Feedback” button on FishPath Tool Dashboard. The user is prompted to categorize their feedback as “Content Related” or “Software Issue”.
2.	Email support@fishpath.org 

##### How does the FishPath Tool content (questions, options, caveats, etc.) get updated? And how often? {#faq-content-updates}

The FishPath team is composed of practicing fisheries managers and scientists who stay up to date on the changing field of fisheries research. The Tool is maintained with the aim of being as current with fishery management practices, science and literature as possible. We also strive to correct any mistakes found in the Tool as quickly as possible. In order to do this, content updates can be made at any time. 

Suggestions from users regarding the content is also greatly appreciated and encouraged. We recognize that fisheries occur in a wide variety of contexts and our small team cannot know every possible scenario and caveat. Any feedback will get a full review and be incorporated into the Tool as needed. 

Every time a user logs in, the Tool will use the most up to date version of the Tool content. No action is needed to receive the updates, even if the questionnaire is already completed. If a new question has been added after a user has completed the questionnaire, a prompt will appear to answer that question before returning to the results screen.

##### How do I stay updated on changes to the FishPath Tool questionnaire or content? {#faq-stay-updated}

A brief summary of any major changes is documented in the biannual newsletter.

An up to date list of all content changes is documented in the [change log](https://github.com/FishPath/FishPath-Tool-User-Guide/blob/master/Major%20Content%20Updates.md). This list contains an overview of major changes such as new or edited questions and options. A detailed spreadsheet of every criteria and caveat change is [located here](https://docs.google.com/spreadsheets/d/1HPlUvI6XuvXtYdFk5bpOsG4JR1fdM0D58KO5mBs0fyE/edit?usp=sharing). It allows you to filter and sort by specific options or questions.

##### Are answers to new questions also updated in “copied fisheries”? {#faq-copy-fisheries}

Once a fishery is copied, changes in the original or copied fishery will have no effect on the other.

##### Does the FishPath Tool need the internet to run? {#faq-internet}

The FishPath Tool does require an internet connection to load and function properly. However, the Tool has been designed to handle poor or intermittent internet connections. Once logged in, the Tool can partially function without the internet. If the internet cuts out or lags while working, the Tool will store any answers to questions or changes made while offline in the browser until it is able to reconnect with the server and save the changes. The [saving status toolbar][Saving Status Toolbar] across the bottom of the screen lets the user know if any changes have not been able to be saved to the server. Closing the window or navigating away from the Tool when there are unsaved changes, will cause those changes to be lost.

##### Why does the number of questions for each section appear to change? {#faq-question-numbering}

Many of the questions in the questionnaire are relevant to multiple sections. Once you answer a question that affects multiple sections, the Tool will not repeat that question again when completing the questionnaire for another section. For example, before starting the questionnaire for any section, there are 41 questions in Data Collection, 50 questions in Assessment, and 44 in Management Measures. A user starts by completing the Data Collection questionnaire. 6 of those questions also apply to Assessment and 14 apply to Management Measures as well. If the user answers the Assessment section next, instead of being asked all 50 questions, only  44 would be asked, since 6 of the questions have already been answered when completing the Data Collection questionnaire. Likewise, if the user answers the Management Measures section next, only 30 questions would be asked.

