# Options

## Data Collection

### Market Surveys{-}
> **Category**: Basic understanding of the fishery
>
> Market surveys are a mechanism for obtaining fishery-dependent information. They are useful when fishery information cannot be obtained on board fishing vessels or at the direct point of offloading, as well as when fishing occurs at remote or disparate locations that are difficult to survey consistently. Market surveys may also be useful when funding or capacity for data-gathering is low, or in situations where there is not a detailed data-collection protocol. Market surveys may encompass a variety of techniques, including visual surveys and interviews, and are intended to gather data on points such as catch composition and species information. Conducting surveys in fish markets can often provide access to merchants or fish buyers who are there purchasing landed fish and transporting catches further along the supply chain. These merchants often have relationships with fishers, allowing possible insight into fishery operational characteristics. If the market is located at or directly near the point of landing, timing and duration of landings may also be recorded. However, care must be used when designing a market survey sampling protocol, as catches displayed at market may not be representative of total catches (by area landed, size of catch, or gears deployed) and do not include at-sea discards.
>
>When very little is known about a fishery, stakeholders may want to start by collecting general fishery information or fishery operational characteristics to gain a basic understanding of it. Where very few resources are available, this may be the only available data type, although efforts should be made to move beyond this and make the most efficient use of available capacity. Information collected can be fishery independent or dependent; it can help stakeholders learn more about the size and composition of the fleet, identify the total fished area, determine the gear types used, identify the species landed, make broad estimates regarding catch or fishing effort, and gather other information to aid in better understanding the fishery.
>
>**Potential Data**
>
>Data that may be collected from this monitoring method include species identification, species composition, and market supply chain.
>
>**Examples**
>
>Visual surveys of catch composition.
Surveys to obtain information on sex ratios or length frequencies.
Biological samples, including gonads or otoliths.
Seller or distributor interviews.
>
>**References**
>
>EDF. (2013). Data collection guide for nearshore fisheries. Environmental Defense Fund. [http://fishe.edf.org/sites/stockassessments.edf.org/files/Data%20Collection%20Guide%20for%20Nearshore%20Fisheries.pdf](http://fishe.edf.org/sites/stockassessments.edf.org/files/Data%20Collection%20Guide%20for%20Nearshore%20Fisheries.pdf) 
>
>Spaet, J. L., & Berumen, M. L. (2015). Fish market surveys indicate unsustainable elasmobranch fisheries in the Saudi Arabian Red Sea. Fisheries Research, 161, 356-364. [http://dx.doi.org/10.1016/j.fishres.2014.08.022](http://dx.doi.org/10.1016/j.fishres.2014.08.022)
>
>Sparre, P. J. (2000). Manual on sample-based data collection for fisheries assessment. Examples from Viet Nam. FAO Fisheries Technical Paper. No. 398. Rome. 171 pp.
>
>White, W. T., Last, P. R., Faizah, R., Chodrijah, U., Buckworth, R. C., & Dichmont, C. M. (2014). Rapid fishery assessment by market survey (RFAMS)-an improved rapid-assessment approach to characterising fish landings in developing countries. PloS one, 9(10), e109182. [https://doi.org/10.1371/journal.pone.0109182](https://doi.org/10.1371/journal.pone.0109182) 



